const data = [
  {
    id: 0,
    picture: "/photos/isac_green.png",
    name: "Case",
    last_name: "Head",
    middle_name: "Leach",
    address: "404 Oxford Walk, Eden, Hawaii, 1649",
    qr_value: "COMTOURS",
  },
  {
    id: 1,
    picture: "/photos/John_Doe.png",
    name: "Smith",
    last_name: "Hurst",
    middle_name: "Craft",
    address: "523 Cortelyou Road, Hegins, 8312",
    qr_value: "VITRICOMP",
  },
  {
    id: 2,
    picture: "/photos/Zara_bree.png",
    name: "Mitzi",
    last_name: "Rush",
    middle_name: "Mcfarland",
    address: "974 Glen Street, New York, 3243",
    qr_value: "DIGIGEN",
  },
  {
    id: 3,
    picture: "/photos/Jeniffer_Larson.png",
    name: "Misty",
    last_name: "Soto",
    middle_name: "Bender",
    address: "183 Wakeman Place, Connecticut",
    qr_value: "COMVEY",
  },
  {
    id: 4,
    picture: "/photos/ninth.png",
    name: "Cathy",
    last_name: "Miranda",
    middle_name: "Beck",
    address: "373 Lefferts Avenue, California",
    qr_value: "NEBULEAN",
  },
  {
    id: 5,
    picture: "/photos/sixth_person.png",
    name: "Evans",
    last_name: "Stokes",
    middle_name: "Trevino",
    address: "144 Prospect Street, Delco, Utah",
    qr_value: "UNCORP",
  },
  {
    id: 6,
    picture: "/photos/tenth.png",
    name: "Jacquelyn",
    last_name: "Collins",
    middle_name: "Hoffman",
    address: "279 Robert Street, Elwood, 4126",
    qr_value: "OPTICON",
  },
  {
    id: 7,
    picture: "/photos/eight.png",
    name: "Berger",
    last_name: "Keith",
    middle_name: "Meyers",
    address: "180 Schweikerts Walk, Kentucky",
    qr_value: "COMFIRM",
  },
  {
    id: 8,
    picture: "/photos/seventh_person.png",
    name: "Aline",
    last_name: "Barry",
    middle_name: "Bright",
    address: "245 Guernsey Street, 4988",
    qr_value: "NEPTIDE",
  },
  {
    id: 9,
    picture: "/photos/joseph.png",
    name: "Josephine",
    last_name: "Moore",
    middle_name: "Hogan",
    address: "476 Ira Court, Blanco,  7517",
    qr_value: "MANUFACT",
  },
  {
    id: 10,
    picture: "/photos/fourth_person.png",
    name: "Martin",
    last_name: "George",
    middle_name: "Frye",
    address: "826 Milton Street, Washington, 5015",
    qr_value: "COMVEYOR",
  },
  {
    id: 11,
    picture: "/photos/first_person.png",
    name: "Kelsey",
    last_name: "Morales",
    middle_name: "Perry",
    address: "626 School Lane, Cecilia, Oregon",
    qr_value: "DUOFLEX",
  },
  {
    id: 12,
    picture: "/photos/third.png",
    name: "Burns",
    last_name: "Ortega",
    middle_name: "Norris",
    address: "146 Clay Street, Faxon, 8883",
    qr_value: "EXOTERIC",
  },
  {
    id: 13,
    picture: "/photos/second_person.png",
    name: "Martha",
    last_name: "Jenkins",
    middle_name: "Dillon",
    address: "135 Chestnut Avenue, Oklahoma",
    qr_value: "ZIPAK",
  },
  {
    id: 14,
    picture: "/photos/twenty.png",
    name: "Addie",
    last_name: "Kirk",
    middle_name: "Farley",
    address: "568 Reeve Place, West Virginia",
    qr_value: "ISOTERNIA",
  },
  {
    id: 15,
    picture: "/photos/sixteen.png",
    name: "Mildred",
    last_name: "Marquez",
    middle_name: "Mccullough",
    address: "535 Noble Street, Tennessee",
    qr_value: "APPLIDECK",
  },
  {
    id: 16,
    picture: "/photos/seventeen.png",
    name: "Maricela",
    last_name: "Blackwell",
    middle_name: "Griffith",
    address: "881 Vandervoort Avenue, 7174",
    qr_value: "INTERODEO",
  },
  {
    id: 17,
    picture: "/photos/eigteen.png",
    name: "Chandra",
    last_name: "Stevens",
    middle_name: "Beasley",
    address: "534 Havens Place, Tioga, Illinois",
    qr_value: "MEMORA",
  },
  {
    id: 18,
    picture: "/photos/twelve.png",
    name: "Summer",
    last_name: "Figueroa",
    middle_name: "Rivas",
    address: "436 Haring Street, Lisco, Georgia",
    qr_value: "QUAREX",
  },
  {
    id: 19,
    picture: "/photos/thirteen.png",
    name: "Olson",
    last_name: "Wiley",
    middle_name: "Young",
    address: "199 Crawford Avenue",
    qr_value: "PHUEL",
  },
  {
    id: 20,
    picture: "/photos/nineteen.png",
    name: "Magdalena",
    last_name: "Aguilar",
    middle_name: "Kemp",
    address: "359 Tudor Terrace, Longoria, 1548",
    qr_value: "INSURESYS",
  },
  {
    id: 21,
    picture: "/photos/fourteen.png",
    name: "Garrison",
    last_name: "Leonard",
    middle_name: "Vincent",
    address: "733 Highland Place, Virginia",
    qr_value: "HONOTRON",
  },
  {
    id: 22,
    picture: "/photos/fifteen.png",
    name: "Lavonne",
    last_name: "Atkinson",
    middle_name: "Strong",
    address: "886 Ferry Place, Chase, Montana",
    qr_value: "JOVIOLD",
  },
  {
    id: 23,
    picture: "/photos/eleven.png",
    name: "Hines",
    last_name: "Newman",
    middle_name: "Banks",
    address: "636 Matthews Place, Ribera,  9779",
    qr_value: "GEEKOLOGY",
  },
  {
    id: 0,
    picture: "/photos/isac_green.png",
    name: "Case",
    last_name: "Head",
    middle_name: "Leach",
    address: "404 Oxford Walk, Eden, Hawaii, 1649",
    qr_value: "COMTOURS",
  },
  {
    id: 1,
    picture: "/photos/John_Doe.png",
    name: "Smith",
    last_name: "Hurst",
    middle_name: "Craft",
    address: "523 Cortelyou Road, Hegins, 8312",
    qr_value: "VITRICOMP",
  },
  {
    id: 2,
    picture: "/photos/Zara_bree.png",
    name: "Mitzi",
    last_name: "Rush",
    middle_name: "Mcfarland",
    address: "974 Glen Street, New York, 3243",
    qr_value: "DIGIGEN",
  },
  {
    id: 3,
    picture: "/photos/Jeniffer_Larson.png",
    name: "Misty",
    last_name: "Soto",
    middle_name: "Bender",
    address: "183 Wakeman Place, Connecticut",
    qr_value: "COMVEY",
  },
  {
    id: 4,
    picture: "/photos/ninth.png",
    name: "Cathy",
    last_name: "Miranda",
    middle_name: "Beck",
    address: "373 Lefferts Avenue, California",
    qr_value: "NEBULEAN",
  },
  {
    id: 5,
    picture: "/photos/sixth_person.png",
    name: "Evans",
    last_name: "Stokes",
    middle_name: "Trevino",
    address: "144 Prospect Street, Delco, Utah",
    qr_value: "UNCORP",
  },
  {
    id: 6,
    picture: "/photos/tenth.png",
    name: "Jacquelyn",
    last_name: "Collins",
    middle_name: "Hoffman",
    address: "279 Robert Street, Elwood, 4126",
    qr_value: "OPTICON",
  },
  {
    id: 7,
    picture: "/photos/eight.png",
    name: "Berger",
    last_name: "Keith",
    middle_name: "Meyers",
    address: "180 Schweikerts Walk, Kentucky",
    qr_value: "COMFIRM",
  },
  {
    id: 8,
    picture: "/photos/seventh_person.png",
    name: "Aline",
    last_name: "Barry",
    middle_name: "Bright",
    address: "245 Guernsey Street, 4988",
    qr_value: "NEPTIDE",
  },
  {
    id: 9,
    picture: "/photos/joseph.png",
    name: "Josephine",
    last_name: "Moore",
    middle_name: "Hogan",
    address: "476 Ira Court, Blanco,  7517",
    qr_value: "MANUFACT",
  },
  {
    id: 10,
    picture: "/photos/fourth_person.png",
    name: "Martin",
    last_name: "George",
    middle_name: "Frye",
    address: "826 Milton Street, Washington, 5015",
    qr_value: "COMVEYOR",
  },
  {
    id: 11,
    picture: "/photos/first_person.png",
    name: "Kelsey",
    last_name: "Morales",
    middle_name: "Perry",
    address: "626 School Lane, Cecilia, Oregon",
    qr_value: "DUOFLEX",
  },
  {
    id: 12,
    picture: "/photos/third.png",
    name: "Burns",
    last_name: "Ortega",
    middle_name: "Norris",
    address: "146 Clay Street, Faxon, 8883",
    qr_value: "EXOTERIC",
  },
  {
    id: 13,
    picture: "/photos/second_person.png",
    name: "Martha",
    last_name: "Jenkins",
    middle_name: "Dillon",
    address: "135 Chestnut Avenue, Oklahoma",
    qr_value: "ZIPAK",
  },
  {
    id: 14,
    picture: "/photos/twenty.png",
    name: "Addie",
    last_name: "Kirk",
    middle_name: "Farley",
    address: "568 Reeve Place, West Virginia",
    qr_value: "ISOTERNIA",
  },
  {
    id: 15,
    picture: "/photos/sixteen.png",
    name: "Mildred",
    last_name: "Marquez",
    middle_name: "Mccullough",
    address: "535 Noble Street, Tennessee",
    qr_value: "APPLIDECK",
  },
  {
    id: 16,
    picture: "/photos/seventeen.png",
    name: "Maricela",
    last_name: "Blackwell",
    middle_name: "Griffith",
    address: "881 Vandervoort Avenue, 7174",
    qr_value: "INTERODEO",
  },
  {
    id: 17,
    picture: "/photos/eigteen.png",
    name: "Chandra",
    last_name: "Stevens",
    middle_name: "Beasley",
    address: "534 Havens Place, Tioga, Illinois",
    qr_value: "MEMORA",
  },
  {
    id: 18,
    picture: "/photos/twelve.png",
    name: "Summer",
    last_name: "Figueroa",
    middle_name: "Rivas",
    address: "436 Haring Street, Lisco, Georgia",
    qr_value: "QUAREX",
  },
  {
    id: 19,
    picture: "/photos/thirteen.png",
    name: "Olson",
    last_name: "Wiley",
    middle_name: "Young",
    address: "199 Crawford Avenue",
    qr_value: "PHUEL",
  },
  {
    id: 20,
    picture: "/photos/nineteen.png",
    name: "Magdalena",
    last_name: "Aguilar",
    middle_name: "Kemp",
    address: "359 Tudor Terrace, Longoria, 1548",
    qr_value: "INSURESYS",
  },
  {
    id: 21,
    picture: "/photos/fourteen.png",
    name: "Garrison",
    last_name: "Leonard",
    middle_name: "Vincent",
    address: "733 Highland Place, Virginia",
    qr_value: "HONOTRON",
  },
  {
    id: 22,
    picture: "/photos/fifteen.png",
    name: "Lavonne",
    last_name: "Atkinson",
    middle_name: "Strong",
    address: "886 Ferry Place, Chase, Montana",
    qr_value: "JOVIOLD",
  },
  {
    id: 23,
    picture: "/photos/eleven.png",
    name: "Hines",
    last_name: "Newman",
    middle_name: "Banks",
    address: "636 Matthews Place, Ribera,  9779",
    qr_value: "GEEKOLOGY",
  },
  {
    id: 0,
    picture: "/photos/isac_green.png",
    name: "Case",
    last_name: "Head",
    middle_name: "Leach",
    address: "404 Oxford Walk, Eden, Hawaii, 1649",
    qr_value: "COMTOURS",
  },
  {
    id: 1,
    picture: "/photos/John_Doe.png",
    name: "Smith",
    last_name: "Hurst",
    middle_name: "Craft",
    address: "523 Cortelyou Road, Hegins, 8312",
    qr_value: "VITRICOMP",
  },
  {
    id: 2,
    picture: "/photos/Zara_bree.png",
    name: "Mitzi",
    last_name: "Rush",
    middle_name: "Mcfarland",
    address: "974 Glen Street, New York, 3243",
    qr_value: "DIGIGEN",
  },
  {
    id: 3,
    picture: "/photos/Jeniffer_Larson.png",
    name: "Misty",
    last_name: "Soto",
    middle_name: "Bender",
    address: "183 Wakeman Place, Connecticut",
    qr_value: "COMVEY",
  },
  {
    id: 4,
    picture: "/photos/ninth.png",
    name: "Cathy",
    last_name: "Miranda",
    middle_name: "Beck",
    address: "373 Lefferts Avenue, California",
    qr_value: "NEBULEAN",
  },
  {
    id: 5,
    picture: "/photos/sixth_person.png",
    name: "Evans",
    last_name: "Stokes",
    middle_name: "Trevino",
    address: "144 Prospect Street, Delco, Utah",
    qr_value: "UNCORP",
  },
  {
    id: 6,
    picture: "/photos/tenth.png",
    name: "Jacquelyn",
    last_name: "Collins",
    middle_name: "Hoffman",
    address: "279 Robert Street, Elwood, 4126",
    qr_value: "OPTICON",
  },
  {
    id: 7,
    picture: "/photos/eight.png",
    name: "Berger",
    last_name: "Keith",
    middle_name: "Meyers",
    address: "180 Schweikerts Walk, Kentucky",
    qr_value: "COMFIRM",
  },
  {
    id: 8,
    picture: "/photos/seventh_person.png",
    name: "Aline",
    last_name: "Barry",
    middle_name: "Bright",
    address: "245 Guernsey Street, 4988",
    qr_value: "NEPTIDE",
  },
  {
    id: 9,
    picture: "/photos/joseph.png",
    name: "Josephine",
    last_name: "Moore",
    middle_name: "Hogan",
    address: "476 Ira Court, Blanco,  7517",
    qr_value: "MANUFACT",
  },
  {
    id: 10,
    picture: "/photos/fourth_person.png",
    name: "Martin",
    last_name: "George",
    middle_name: "Frye",
    address: "826 Milton Street, Washington, 5015",
    qr_value: "COMVEYOR",
  },
  {
    id: 11,
    picture: "/photos/first_person.png",
    name: "Kelsey",
    last_name: "Morales",
    middle_name: "Perry",
    address: "626 School Lane, Cecilia, Oregon",
    qr_value: "DUOFLEX",
  },
  {
    id: 12,
    picture: "/photos/third.png",
    name: "Burns",
    last_name: "Ortega",
    middle_name: "Norris",
    address: "146 Clay Street, Faxon, 8883",
    qr_value: "EXOTERIC",
  },
  {
    id: 13,
    picture: "/photos/second_person.png",
    name: "Martha",
    last_name: "Jenkins",
    middle_name: "Dillon",
    address: "135 Chestnut Avenue, Oklahoma",
    qr_value: "ZIPAK",
  },
  {
    id: 14,
    picture: "/photos/twenty.png",
    name: "Addie",
    last_name: "Kirk",
    middle_name: "Farley",
    address: "568 Reeve Place, West Virginia",
    qr_value: "ISOTERNIA",
  },
  {
    id: 15,
    picture: "/photos/sixteen.png",
    name: "Mildred",
    last_name: "Marquez",
    middle_name: "Mccullough",
    address: "535 Noble Street, Tennessee",
    qr_value: "APPLIDECK",
  },
  {
    id: 16,
    picture: "/photos/seventeen.png",
    name: "Maricela",
    last_name: "Blackwell",
    middle_name: "Griffith",
    address: "881 Vandervoort Avenue, 7174",
    qr_value: "INTERODEO",
  },
  {
    id: 17,
    picture: "/photos/eigteen.png",
    name: "Chandra",
    last_name: "Stevens",
    middle_name: "Beasley",
    address: "534 Havens Place, Tioga, Illinois",
    qr_value: "MEMORA",
  },
  {
    id: 18,
    picture: "/photos/twelve.png",
    name: "Summer",
    last_name: "Figueroa",
    middle_name: "Rivas",
    address: "436 Haring Street, Lisco, Georgia",
    qr_value: "QUAREX",
  },
  {
    id: 19,
    picture: "/photos/thirteen.png",
    name: "Olson",
    last_name: "Wiley",
    middle_name: "Young",
    address: "199 Crawford Avenue",
    qr_value: "PHUEL",
  },
  {
    id: 20,
    picture: "/photos/nineteen.png",
    name: "Magdalena",
    last_name: "Aguilar",
    middle_name: "Kemp",
    address: "359 Tudor Terrace, Longoria, 1548",
    qr_value: "INSURESYS",
  },
  {
    id: 21,
    picture: "/photos/fourteen.png",
    name: "Garrison",
    last_name: "Leonard",
    middle_name: "Vincent",
    address: "733 Highland Place, Virginia",
    qr_value: "HONOTRON",
  },
  {
    id: 22,
    picture: "/photos/fifteen.png",
    name: "Lavonne",
    last_name: "Atkinson",
    middle_name: "Strong",
    address: "886 Ferry Place, Chase, Montana",
    qr_value: "JOVIOLD",
  },
  {
    id: 23,
    picture: "/photos/eleven.png",
    name: "Hines",
    last_name: "Newman",
    middle_name: "Banks",
    address: "636 Matthews Place, Ribera,  9779",
    qr_value: "GEEKOLOGY",
  },
];

export default data;
